name: hasura_cache_interceptor
description: Package to implements cache in Hasura package
version: 1.0.0-dev.4
author: F-Team <david@flutterando.com.br>
homepage: https://flutterando.com.br
repository: https://github.com/Flutterando/hasura_cache_interceptor

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  uuid: ^3.0.0-nullsafety.1
  hasura_connect: ^3.0.0-nullsafety.0

dev_dependencies:
  http: ^0.13.0-nullsafety.0
  mocktail: ^0.0.1-dev.11
  #mockito: ^4.1.1
  test: ^1.16.0-nullsafety.19
